### ISSUE TITLE
Take advantage of administrate "selectize" usage

### ISSUE THREAD

**Issue by Kulgar** [blocknotes/administrate_ransack#13]
Another  suggestion would be to reuse the selectize js lib within this gem for select fields. 
Maybe we could think about an option to activate  / deactivate selectize per field and/or globally. 

And the option could be activated by default.
What do you think?

**Comment by blocknotes** [comment]
Hi @Kulgar, I reply a bit late 😅 
Yeah, it could be useful to use Selectize.
I'm experimenting here: https://github.com/blocknotes/administrate_ransack/pull/14

**Comment by blocknotes** [comment]
Applied in the release [0.3.4](https://github.com/blocknotes/administrate_ransack/releases/tag/v0.3.4) ✅

**Comment by Kulgar** [comment]
@blocknotes : thanks! :-)
