### ISSUE TITLE
Can not work with Rails7.1

### ISSUE THREAD

**Issue by raykin** [blocknotes/administrate_ransack#29]
Application crashed at start with info:

! Unable to load application: LoadError: cannot load such file -- polyamorous/activerecord_7.1_ruby_2/join_association
15:44:39 web.1  | /Users/raykin/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require': cannot load such file -- polyamorous/activerecord_7.1_ruby_2/join_association (LoadError)

Maybe it's because ransack dependency block?

**Comment by blocknotes** [comment]
Hey @raykin,
sorry for the late feedback: Rails 7.1 is working - in the CI I recently enabled the test workflow for it.

From your logs you are using Ruby 3.3.x ?
I haven't tested it yet - so it could be related to it 🤔

**Comment by raykin** [comment]
Close it because I didn't reproduce this crash in my recent trial. Btw I use Ruby 3.3.4 now.
