### ISSUE TITLE
undefined method `amount_eq' for Ransack::Search

### ISSUE THREAD

**Issue by rwehresmann** [blocknotes/administrate_ransack#9]
Hi! I just tried the gem but there is an issue with it:

`undefined method amount_eq' for Ransack::Search<class: Deposit, base: Grouping <combinator: and>>:Ransack::Search` raised from `<%= render('administrate_ransack/filters') %>` .

I followed the installation guide, Is there something more I need to do?

**Comment by MistarzJan** [comment]
@rwehresmann  Have you managed to solve the issue?
EDIT: NVM, i've figured it out. For future googlers: make sure you use the right predicate and attribute name
